# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getChangePoints <- function(data, method = "FOCuS0", cost = "gauss", common_difference_step = 1L, common_ratio_step = 1L, first_step_qhull = 5L, cand_nb = FALSE, opt_changes = FALSE, opt_costs = FALSE, cands = FALSE) {
    .Call(`_focus_getChangePoints`, data, method, cost, common_difference_step, common_ratio_step, first_step_qhull, cand_nb, opt_changes, opt_costs, cands)
}

