# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getChangePoints <- function(data, method = "FOCuS0", cost = "gauss", step = 1L, cand_nb = FALSE, opt_changes = FALSE, opt_costs = FALSE) {
    .Call(`_focus_getChangePoints`, data, method, cost, step, cand_nb, opt_changes, opt_costs)
}

